image: debian:stretch

build:
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install gcc git python3 python3-markdown
    - apt-get -y install ruby-sass ghc help2man
    - apt-get -y install texlive
    - git config --global user.email "testing-on-gitlab-ci@example.com"
    - git config --global user.name "CI Builder"
  script:
    - sh build/linux.sh
    - ./fac
  artifacts:
    paths:
      - fac
  cache:
    paths:
      - "/var/cache/apt/archives/*.deb"

# run tests using the binary built before
test:
  stage: test
  before_script:
    - apt-get update
    - apt-get -y install gcc git python3 python3-markdown
    - apt-get -y install ruby-sass ghc help2man
    - apt-get -y install texlive gcovr libc6-dev-i386
    - git config --global user.email "testing-on-gitlab-ci@example.com"
    - git config --global user.name "CI Builder"
  script:
    - python3 run-tests.py -v
  cache:
    paths:
      - "/var/cache/apt/archives/*.deb"

