#!/bin/sh

set -ev

echo $0

# This test ensures that exhaustive will fail if we do not include in the
# facfile an input that is generated by another rule.

rm -rf $0.dir
mkdir $0.dir
cd $0.dir

cat > top.fac <<EOF
| echo foo > foo

| cat foo extra > bar

| cp foo baz
< foo
EOF

echo extra > extra

git init
git add top.fac extra

if ../../fac --exhaustive &> fac.out; then
    cat fac.out
    echo this should fail due to exhaustive strictness
    exit 1
fi

cat fac.out
grep 'missing dependency' fac.out
grep 'requires' fac.out

cat > top.fac <<EOF
| echo foo > foo

| cat foo extra > bar
< foo

| cp foo baz
< foo
EOF

if ../../fac --exhaustive &> fac.out; then
    cat fac.out
    echo this should fail due to exhaustive strictness
    exit 1
fi

cat fac.out
grep 'missing dependency' fac.out
grep 'requires extra' fac.out

cat > top.fac <<EOF
| echo foo > foo

| cat foo extra > bar
< extra

| cp foo baz
< foo
EOF

if ../../fac --exhaustive &> fac.out; then
    cat fac.out
    echo this should fail due to exhaustive strictness
    exit 1
fi

cat fac.out
grep 'missing dependency' fac.out
grep 'requires foo' fac.out

cat > top.fac <<EOF
| echo foo > foo

| cat foo extra > bar
< foo
< extra

| cp foo baz
< foo
EOF

../../fac --exhaustive

grep foo bar

exit 0
